In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/text-summriaztion/text_summary.csv


In [2]:
#pip install nltk

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import nltk 
nltk.download('punkt')
import re 
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [8]:
path='/kaggle/input/text-summriaztion/'
df=pd.read_csv(path+'text_summary.csv')

In [9]:
df.head()

article_id                                       article_text  \
0           1  Maria Sharapova has basically no friends as te...   
1           2  BASEL, Switzerland (AP), Roger Federer advance...   
2           3  Roger Federer has revealed that organisers of ...   
3           4  Kei Nishikori will try to end his long losing ...   
4           5  Federer, 37, first broke through on tour over ...   

                                              source  
0  https://www.tennisworldusa.org/tennis/news/Mar...  
1  http://www.tennis.com/pro-game/2018/10/copil-s...  
2  https://scroll.in/field/899938/tennis-roger-fe...  
3  http://www.tennis.com/pro-game/2018/10/nishiko...  
4  https://www.express.co.uk/sport/tennis/1036101...

In [10]:
print(df.shape)

(8, 3)


In [11]:
df['article_text'][1]

"BASEL, Switzerland (AP), Roger Federer advanced to the 14th Swiss Indoors final of his career by beating seventh-seeded Daniil Medvedev 6-1, 6-4 on Saturday. Seeking a ninth title at his hometown event, and a 99th overall, Federer will play 93th-ranked Marius Copil on Sunday. Federer dominated the 20th-ranked Medvedev and had his first match-point chance to break serve again at 5-1. He then dropped his serve to love, and let another match point slip in Medvedev's next service game by netting a backhand. He clinched on his fourth chance when Medvedev netted from the baseline. Copil upset expectations of a Federer final against Alexander Zverev in a 6-3, 6-7 (6), 6-4 win over the fifth-ranked German in the earlier semifinal. The Romanian aims for a first title after arriving at Basel without a career win over a top-10 opponent. Copil has two after also beating No. 6 Marin Cilic in the second round. Copil fired 26 aces past Zverev and never dropped serve, clinching after 2 1/2 hours with

In [18]:
word_embeddings = {}
path2='../input/glove6b100dtxt/'
f = open(path2+'glove.6B.100d.txt', encoding='utf-8')

In [19]:
for line in f: 
    values=line.split()
    word=values[0]
    coefs=np.asarray(values[1:],dtype='float32')
    word_embeddings[word]=coefs
f.close()

In [22]:
word_embeddings['person'] 

array([ 0.38709  ,  0.32629  ,  0.64524  ,  0.012882 , -0.11051  ,
        1.1922   ,  0.37298  ,  0.12726  ,  0.43991  ,  0.086266 ,
        0.0039535, -0.049873 ,  0.81426  , -0.33466  ,  0.17671  ,
       -0.18838  , -0.11255  ,  0.18719  , -0.50361  ,  0.74282  ,
        0.33397  , -0.19284  , -0.29303  , -0.4946   ,  0.15614  ,
       -0.085108 , -0.024602 , -0.38991  ,  0.229    ,  0.25051  ,
        0.10483  ,  1.1478   ,  0.11177  , -0.43257  ,  0.4302   ,
        0.046693 , -0.75141  ,  0.31403  ,  0.69889  ,  0.12507  ,
       -0.42615  ,  0.12931  ,  0.82835  , -0.34128  , -0.20273  ,
        0.19026  , -0.14324  , -0.65663  , -0.6439   , -0.90877  ,
        0.55001  , -0.37747  ,  0.76323  ,  1.0133   , -0.27997  ,
       -1.7108   ,  0.1313   , -0.2171   ,  1.8132   ,  0.3366   ,
        0.16273  ,  0.8153   , -0.28179  , -0.21643  ,  0.74052  ,
        0.084269 ,  0.66184  , -0.0031966,  0.18784  , -0.3492   ,
       -0.24641  , -0.46574  ,  0.3723   ,  0.04385  ,  0.7750

In [35]:
from nltk.tokenize import sent_tokenize
sentences=[]

sentences = []
for s in df['article_text']:
    sentences.append(sent_tokenize(s))

sentences = [y for x in sentences for y in x]


Cleaning the datasets

In [46]:
clean_sentences=pd.Series(sentences).str.replace('[^a-zA-Z]',' ')
clean_sentences = [s.lower() for s in clean_sentences]
stop_words = stopwords.words('english')
def remove_stopwords(sen):
    sen_new=' '.join([i for i in sen if i not in stop_words])
    
    return sen_new
    

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


In [47]:
clean_sentences=[remove_stopwords(r.split()) for r in clean_sentences]

In [48]:
clean_sentences[1]

'russian player problems openly speaking recent interview said really hide feelings much'

In [49]:
sentence_vectors = []
for i in clean_sentences:
  if len(i) != 0:
    v = sum([word_embeddings.get(w, np.zeros((100,))) for w in i.split()])/(len(i.split())+0.001)
  else:
    v = np.zeros((100,))
  sentence_vectors.append(v)

In [54]:
sentence_vectors[1]

array([-8.46056044e-02,  1.69623360e-01,  4.33749944e-01, -8.58418122e-02,
       -1.70975417e-01,  1.32896423e-01, -2.54114658e-01, -1.70107469e-01,
        2.79757172e-01,  6.33887276e-02, -2.04101473e-01,  7.64638111e-02,
        2.85677612e-01, -9.00602564e-02, -1.14498213e-01, -9.90290865e-02,
       -1.34927511e-01, -2.71166232e-03, -4.13565874e-01,  6.32358193e-02,
        4.55082878e-02,  1.91257671e-01, -1.39448941e-01, -1.13781996e-03,
       -9.70350802e-02, -1.26338288e-01, -5.15491217e-02, -3.08907747e-01,
        3.43927354e-01,  2.86936820e-01, -2.22957656e-01,  4.46837395e-01,
       -1.11253977e-01, -7.21814632e-02,  1.37357712e-01,  1.71515450e-01,
        5.39051816e-02,  2.76359648e-01, -2.55537611e-02, -1.31975263e-02,
       -4.84045923e-01, -1.34829834e-01,  2.57399052e-01, -1.33780092e-01,
       -2.33958840e-01, -1.68721929e-01,  2.29427516e-01, -3.33674073e-01,
       -2.39330102e-02, -7.64521301e-01,  2.71977514e-01, -9.60583910e-02,
        1.57525614e-01,  

Finding Similarities to Summarize Text
The next step is to find similarities between the sentences, and I will use the cosine similarity approach for this task. Let’s create an empty similarity matrix for this task and fill it with cosine similarities of sentences:

In [55]:
sim_mat = np.zeros([len(sentences), len(sentences)])
from sklearn.metrics.pairwise import cosine_similarity
for i in range(len(sentences)):
  for j in range(len(sentences)):
    if i != j:
      sim_mat[i][j] = cosine_similarity(sentence_vectors[i].reshape(1,100), sentence_vectors[j].reshape(1,100))[0,0]

In [56]:
sim_mat

array([[0.        , 0.64378339, 0.59156996, ..., 0.72776717, 0.5850122 ,
        0.68277591],
       [0.64378339, 0.        , 0.83267683, ..., 0.77598292, 0.79842889,
        0.87404495],
       [0.59156996, 0.83267683, 0.        , ..., 0.73326033, 0.75388014,
        0.8130123 ],
       ...,
       [0.72776717, 0.77598292, 0.73326033, ..., 0.        , 0.74423134,
        0.87150967],
       [0.5850122 , 0.79842889, 0.75388014, ..., 0.74423134, 0.        ,
        0.78779906],
       [0.68277591, 0.87404495, 0.8130123 , ..., 0.87150967, 0.78779906,
        0.        ]])

In [57]:
import networkx as nx

nx_graph = nx.from_numpy_array(sim_mat)
scores = nx.pagerank(nx_graph)

In [58]:
scores

{0: 0.008072651812837249,
 1: 0.008501993305467095,
 2: 0.007811931832998158,
 3: 0.009293791287246101,
 4: 0.007500319341702238,
 5: 0.008146814822101289,
 6: 0.008477413410840564,
 7: 0.008251000778010125,
 8: 0.008596957831776629,
 9: 0.00825714424529151,
 10: 0.0012695751770095795,
 11: 0.008860552382933833,
 12: 0.008083543253002173,
 13: 0.008156804670239782,
 14: 0.00844331689249351,
 15: 0.00855689304327121,
 16: 0.007812826598034563,
 17: 0.008071958126597788,
 18: 0.008406020981041979,
 19: 0.008847892197876472,
 20: 0.008860865272110666,
 21: 0.0074219170502842395,
 22: 0.00822343401476627,
 23: 0.008991766362928408,
 24: 0.008463970416187735,
 25: 0.0067018981235010605,
 26: 0.008232471583451702,
 27: 0.008913135597756963,
 28: 0.009061683003650822,
 29: 0.009093905759714915,
 30: 0.009244521571573308,
 31: 0.008994323928725814,
 32: 0.007236869161912383,
 33: 0.00870909302347104,
 34: 0.008919130492987544,
 35: 0.009097421441929054,
 36: 0.007715970772210733,
 37: 0.008883

In [66]:
#lets summarize the text
ranked_sentences = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
for i in range(4):
  print("ARTICLE:")
  print(df['article_text'][i])
  print('\n')
  print("SUMMARY:")
  print(ranked_sentences[i][1])
  print('\n')

ARTICLE:
Maria Sharapova has basically no friends as tennis players on the WTA Tour. The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much. I think everyone knows this is my job here. When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net.So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match. I'm a pretty competitive girl. I say my hellos, but I'm not sending any players flowers as well. Uhm, I'm not really friendly or close to many players. I have not a lot of friends away from the courts.' When she said she is not really close to a lot of players, is that something strategic that she is doing? Is it different on the men's tour than the women's tour? 'No, not at all. I think just because you're in t